### ISSUE TITLE
[Feature Request] Provide examples for secure a rest API via (login/cookie)

### ISSUE THREAD

**Issue by toni-moreno** [go-macaron/session#18]
I'm working with go-macaron and we are define a REST API but it is completely open to the wold I can not block  any HTTP request from anywhere.

I would like let request enter only if valid cookie and only valid cookie if  a POST is done in "/ogin" URL with valid {"username": "XXXX" , "password" , "YYYY" } data.

There is anywhere with a simple example on how can we do this?

I can not find any simple example.

Thank you very much

**Comment by Unknwon** [comment]
Hi, [this is a very simple illustration](https://go-macaron.com/docs/intro/core_concepts#middleware-handlers) of how you should use middleware do this kind of check.
