### ISSUE TITLE
panic: sql: Register called twice for driver postgres

### ISSUE THREAD

**Issue by dgellow** [go-macaron/session#19]
Hi,

I'm already using postgres for my data and now want to use the same driver for my sessions. Unfortunately I cannot just import `"github.com/go-macaron/session/postgres"` as I already have `"github.com/mattes/migrate/driver/postgres"` somewhere else in my code. If I use both import statements I get the expected error

```
panic: sql: Register called twice for driver postgres
```

If I don't import the macaron/session driver I get

```
panic: session: unknown provider 'postgres'(forgotten import?)
```

What's the correct way to solve that situation?

**Comment by Unknwon** [comment]
Hmm... Maybe you should split the code up? Or use another adapter for Macaron session.

**Comment by dgellow** [comment]
FYI, I've also asked the question (in a more general way) there  https://github.com/lib/pq/issues/569.
Let's see if they have a solution to suggest.

**Comment by Unknwon** [comment]
Sure... I guess they would ask you to only choose one of drivers or rewrite Macaron session/migrate app. :trollface:

**Comment by dgellow** [comment]
I close the issue as you provided a pragmatic solution and lib/pq's maintainers haven't responded to https://github.com/lib/pq/issues/569
