### ISSUE TITLE
Reduce permissions of file store

### ISSUE THREAD

**Issue by aaronjwood** [go-macaron/session#20]
Related to our recent discussion at https://github.com/gogits/gogs/issues/3363 can we change the default permissions to be much more restrictive? `os.ModePerm` is 0777 which is world writeable, world readable, and world executable. I wouldn't mind contributing a patch for this if you're open to this change.

Can we change this to 0600 for files (read/write for the owner only) and 0700 for directories (read/write/execute for the owner only)?

**Comment by aaronjwood** [comment]
Also, can we change things like this https://github.com/go-macaron/session/blob/master/file.go#L132 so that we're only using the privileges that are needed?

**Comment by Unknwon** [comment]
`0700` sounds good to me, please send a PR :D

**Comment by Unknwon** [comment]
Closed by #21.
